version: '3'

services:
  # https://hub.docker.com/r/bitnami/postgresql
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=myusername
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=app

  # https://hub.docker.com/r/bitnami/zookeeper
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  postgresql_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
